#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ble_mesh
EXTRA_COMPONENT_DIRS := /d/iotcode/libraries/extra_components/esp-idf-lib/components
include $(IDF_PATH)/make/project.mk

